[workspace]
git_release_enable = false
dependencies_update = true # run `cargo update` in the release PR

git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]] # the double square brackets define a TOML table array
name = "better-config" # name of the package to configure
# set the path of the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"
git_release_enable = true # create GitHub release