[package]
name = "better-config-loader"
version.workspace = true
categories.workspace = true
edition.workspace = true
description.workspace = true
keywords.workspace = true
authors.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["dotenv"]
# dep = ["some_crate"]
dotenv = ["dotenvy"]

[dependencies]
better-config-core.workspace = true
dotenvy = { version = "0.15.7", optional = true }
